syntax on
set number
"set list
"set listchars=tab:··\|,space:·,trail:·,extends:…,precedes:…
":nmap <leader>l :set invlist<cr>
set list listchars=tab:\ \ ┊,trail:·,extends:…,precedes:…
set tags=tags;/
set ignorecase
set smartcase

source ~/.vim/maps/cscope_maps.vim
source ~/.vim/plugins/cctree.vim

function! LoadCscope()
  let db = findfile("cscope.out", ".;")
  if (!empty(db))
    let path = strpart(db, 0, match(db, "/cscope.out$"))
    set nocscopeverbose " suppress 'duplicate connection' error
    exe "cs add " . db . " " . path
    set cscopeverbose
  " else add the database pointed to by environment variable 
  elseif $CSCOPE_DB != "" 
    cs add $CSCOPE_DB
  endif
endfunction
au BufEnter /* call LoadCscope()
